import {test,expect} from '@playwright/test';
const portal='/portal?'+new URLSearchParams({clientMac:'AA:00:00:00:00:11',apMac:'AA:BB:CC:DD:EE:01',site:'babu-shop',ssidName:'BABU-SHOP WIFI',radioId:'0'});
test('mobile portal is local-only and clearly simulated',async({page})=>{await page.setViewportSize({width:390,height:844});const origins=new Set<string>();page.on('request',r=>origins.add(new URL(r.url()).origin));await page.goto('/portal');await expect(page.getByRole('heading',{name:'A little code. A world online.'})).toBeVisible();await expect(page.getByText('SIMULATION · No real internet is authorized')).toBeVisible();await expect(page.getByRole('button',{name:'Connect to Wi-Fi'})).toBeDisabled();expect([...origins]).toEqual([new URL(page.url()).origin]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('staff login, package, batch, unsold rejection, sale, receipt and activation',async({page})=>{
 if(!process.env.E2E_EMAIL||!process.env.E2E_PASSWORD)throw new Error('Set E2E_EMAIL and E2E_PASSWORD for an enabled administrator in the local mock deployment');
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(process.env.E2E_EMAIL);await page.getByLabel('Password',{exact:true}).fill(process.env.E2E_PASSWORD);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByRole('heading',{name:'Good connections start here.'})).toBeVisible();
 await page.getByRole('link',{name:'Packages',exact:true}).click();await page.getByRole('button',{name:'New package'}).click();const name='Browser package '+Date.now();await page.getByLabel('Name',{exact:true}).fill(name);await page.getByLabel('Price (whole TZS)').fill('1200');await page.getByLabel('Duration',{exact:true}).fill('1');await page.getByRole('button',{name:'Save package'}).click();await expect(page.getByText('Package saved. Existing voucher terms stay unchanged.')).toBeVisible();
 await page.getByRole('link',{name:'Voucher Batches',exact:true}).click();await page.getByRole('combobox',{name:'Package',exact:true}).selectOption({label:name+' · TZS 1,200'});await page.getByLabel('Quantity',{exact:true}).fill('2');await page.getByLabel('Batch label').fill(name);await page.getByRole('button',{name:'Generate vouchers'}).click();await expect(page.getByText('Voucher batch created.')).toBeVisible();const row=page.getByRole('row').filter({hasText:name});await row.getByRole('button',{name:'Print batch'}).click();await expect(page.locator('.printed-voucher')).toHaveCount(2);const unsold=(await page.locator('.voucher-code').first().textContent())!;
 await page.goto(portal);await page.getByLabel('Your voucher code').fill(unsold);await page.getByRole('button',{name:'Connect to Wi-Fi'}).click();await expect(page.getByRole('alert')).toContainText('Voucher cannot be used');
 await page.goto('/sell');await page.getByRole('combobox',{name:'Package',exact:true}).selectOption({label:name+' · TZS 1,200 · 2 available'});await page.getByRole('button',{name:'Reserve stock'}).click();await expect(page.getByRole('heading',{name:'Confirm the cash sale'})).toBeVisible();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Record sale'}).click();await expect(page.getByRole('heading',{name:'Cash sale receipt'})).toBeVisible();await expect(page.locator('.printed-voucher')).toHaveCount(1);const sold=(await page.locator('.voucher-code').textContent())!;
 await page.emulateMedia({media:'print'});await expect(page.locator('.sidebar')).toBeHidden();await page.emulateMedia({media:'screen'});
 await page.goto(portal);await page.getByLabel('Your voucher code').fill(sold);await page.getByRole('button',{name:'Connect to Wi-Fi'}).click();await expect(page.getByRole('heading',{name:'You’re authorized'})).toBeVisible({timeout:15000});
 await page.goto('/sales');await expect(page.getByRole('heading',{name:'Cash sales'})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
