import {authorizeRadius} from '../packages/database/src/radius-access.ts';
import {recordAccounting} from '../packages/database/src/record-accounting.ts';
import {normalize} from '../packages/database/src/crypto.ts';
import {beforeAll,afterAll,it,expect} from 'vitest';
import {readFile,readdir} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {pool,SITE,type Staff} from '../packages/database/src/index.ts';
import {generateBatch,reserve,sell,reveal,reverse} from '../packages/database/src/sales.ts';
import {createContext,redeem,status,processOne,housekeeping,revoke} from '../packages/database/src/access.ts';
import {MockAdapter,MikroTikRadiusAdapter} from '../packages/omada/src/index.ts';
import {buildApp} from '../apps/api/src/app.ts';
const admin:Staff={id:randomUUID(),role:'ADMIN',display_name:'Test admin',enabled:true},cashier:Staff={id:randomUUID(),role:'CASHIER',display_name:'Test cashier',enabled:true};
const ctx={clientMac:'AA:00:00:00:00:01',apMac:'AA:BB:CC:DD:EE:01',site:'babu-shop',ssidName:'BABU-SHOP WIFI',radioId:'0'};
let app:Awaited<ReturnType<typeof buildApp>>;
beforeAll(async()=>{const url=new URL(process.env.DATABASE_URL!);if(!url.pathname.endsWith('_test')||!['127.0.0.1','localhost'].includes(url.hostname))throw new Error('Integration tests require an isolated local database whose name ends in _test');
 await pool.query("create schema if not exists auth; create table if not exists auth.users(id uuid primary key); do $$ begin if not exists(select from pg_roles where rolname='anon') then create role anon; end if; if not exists(select from pg_roles where rolname='authenticated') then create role authenticated; end if; end $$; drop schema if exists wifi cascade");
 for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await pool.query(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));await pool.query(await readFile(new URL('../supabase/seed.sql',import.meta.url),'utf8'));
 for(const s of [admin,cashier]){await pool.query('insert into auth.users(id) values($1) on conflict do nothing',[s.id]);await pool.query('insert into wifi.staff_profiles(id,display_name,role) values($1,$2,$3)',[s.id,s.display_name,s.role]);}
 app=await buildApp({adapter:new MockAdapter(),verifyToken:async t=>t==='admin'?admin.id:t==='cashier'?cashier.id:null});
});
afterAll(async()=>{await app?.close();await pool.end();});
async function stock(quantity=1){const p=(await pool.query('insert into wifi.packages(site_id,name,price_tzs,duration_minutes) values($1,$2,1000,60) returning *',[SITE,'Test '+randomUUID()])).rows[0];const b=await generateBatch(admin,{package_id:p.id,quantity});const codes=await reveal(admin,{batch_id:b.id});return {p,b,codes};}
async function sold(){const s=await stock(),r=await reserve(cashier,{package_id:s.p.id,quantity:1}),sale=await sell(cashier,{reservation_id:r.id,cash_received:true},randomUUID());return {...s,sale};}
async function activate(code:string,scenario='success',context=ctx){const c=await createContext(context),r=await redeem(code,c.context_token);await processOne(new MockAdapter(scenario));return {r,state:await status(r.status_token)};}
it('real constraints preserve voucher terms and history',async()=>{const s=await stock();await pool.query('update wifi.packages set price_tzs=9999,name=$2 where id=$1',[s.p.id,'Edited']);expect((await pool.query('select price_tzs,package_name from wifi.vouchers where batch_id=$1',[s.b.id])).rows[0]).toMatchObject({price_tzs:1000,package_name:s.p.name});await expect(pool.query('update wifi.vouchers set price_tzs=2 where batch_id=$1',[s.b.id])).rejects.toThrow('immutable');});
it('unsold vouchers cannot authorize',async()=>{const s=await stock(),c=await createContext(ctx);await expect(redeem(s.codes[0].code,c.context_token)).rejects.toThrow('cannot be used');});
it('duplicate sale requests create exactly one sale',async()=>{const s=await stock(),r=await reserve(cashier,{package_id:s.p.id,quantity:1}),key=randomUUID(),body={reservation_id:r.id,cash_received:true};const result=await Promise.all([sell(cashier,body,key),sell(cashier,body,key)]);expect(result[0].id).toBe(result[1].id);expect((await pool.query('select count(*)::int n from wifi.manual_sales where reservation_id=$1',[r.id])).rows[0].n).toBe(1);await expect(sell(cashier,{...body,notes:'different'},key)).rejects.toThrow('different');});
it('concurrent cashiers cannot reserve the same voucher',async()=>{const s=await stock();const results=await Promise.allSettled([reserve(cashier,{package_id:s.p.id,quantity:1}),reserve(admin,{package_id:s.p.id,quantity:1})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);});
it('concurrent devices cannot bind the same sold voucher',async()=>{const s=await sold(),c1=await createContext(ctx),c2=await createContext({...ctx,clientMac:'AA:00:00:00:00:02'});const r=await Promise.allSettled([redeem(s.codes[0].code,c1.context_token),redeem(s.codes[0].code,c2.context_token)]);expect(r.filter(v=>v.status==='fulfilled')).toHaveLength(1);await processOne(new MockAdapter());});
it('mock activation and reconnect retain the exact original deadline',async()=>{const s=await sold(),first=await activate(s.codes[0].code);expect(first.state.state).toBe('ACTIVE');const second=await activate(s.codes[0].code);expect(second.state.state).toBe('ACTIVE');expect(second.state.expires_at).toEqual(first.state.expires_at);const c=await createContext({...ctx,clientMac:'AA:00:00:00:00:03'});await expect(redeem(s.codes[0].code,c.context_token)).rejects.toThrow('cannot be used');});
it('rejection never produces ACTIVE',async()=>{const s=await sold(),r=await activate(s.codes[0].code,'rejection');expect(r.state.state).toBe('NEEDS_REVIEW');expect(r.state.attempt_state).toBe('REJECTED');});
it('timeouts keep binding and cannot be reversed or blindly retried',async()=>{const s=await sold(),r=await activate(s.codes[0].code,'timeout');expect(r.state.state).toBe('NEEDS_REVIEW');await expect(reverse(admin,s.sale.id,'Customer returned code')).rejects.toThrow('unused');const c=await createContext(ctx);await redeem(s.codes[0].code,c.context_token);expect((await pool.query('select count(*)::int n from wifi.authorization_attempts a join wifi.access_grants g on g.id=a.grant_id where g.voucher_id=$1',[s.codes[0].id])).rows[0].n).toBe(1);});
it('worker recovers unsent durable work and quarantines interrupted sends',async()=>{const s=await sold(),c=await createContext(ctx),r=await redeem(s.codes[0].code,c.context_token);await pool.query("update wifi.jobs set state='LEASED',lease_until=now()-interval '1 second' where attempt_id in (select a.id from wifi.authorization_attempts a join wifi.access_grants g on g.id=a.grant_id where g.voucher_id=$1)",[s.codes[0].id]);const adapter=new MockAdapter();await processOne(adapter);expect(adapter.calls).toBe(0);expect((await status(r.status_token)).state).toBe('NEEDS_REVIEW');});
it('sale reversal retains immutable receipt, voids codes and audits',async()=>{const s=await sold();await reverse(admin,s.sale.id,'Cash returned before use');expect((await pool.query('select inventory_state from wifi.vouchers where id=$1',[s.codes[0].id])).rows[0].inventory_state).toBe('VOID');expect((await pool.query('select * from wifi.manual_sales where id=$1',[s.sale.id])).rowCount).toBe(1);await expect(pool.query('delete from wifi.manual_sales where id=$1',[s.sale.id])).rejects.toThrow('Historical');const c=await createContext(ctx);await expect(redeem(s.codes[0].code,c.context_token)).rejects.toThrow('cannot be used');});
it('revocation blocks future access without claiming a network disconnect',async()=>{const s=await sold();await activate(s.codes[0].code);const g=(await pool.query('select id from wifi.access_grants where voucher_id=$1',[s.codes[0].id])).rows[0];expect((await revoke(admin,g.id,'Operator request')).message).toContain('may continue');const c=await createContext(ctx);await expect(redeem(s.codes[0].code,c.context_token)).rejects.toThrow();});
it('expired deadlines reject new authorization',async()=>{const s=await sold();await pool.query("insert into wifi.access_grants(voucher_id,client_mac,state,proposed_expires_at) values($1,$2,'PENDING',now()-interval '1 second')",[s.codes[0].id,ctx.clientMac]);await housekeeping();const c=await createContext(ctx);await expect(redeem(s.codes[0].code,c.context_token)).rejects.toThrow();});
it('backend enforces cashier permissions and own-sale printing',async()=>{const p=await app.inject({method:'POST',url:'/api/v1/packages',headers:{authorization:'Bearer cashier'},payload:{name:'Bad',price_tzs:1000,duration_minutes:60}});expect(p.statusCode).toBe(403);const s=await stock();expect((await app.inject({method:'POST',url:'/api/v1/vouchers/'+s.codes[0].id+'/reveal',headers:{authorization:'Bearer cashier'},payload:{}})).statusCode).toBe(403);});
it('disabled staff are denied with an otherwise valid token',async()=>{await pool.query('update wifi.staff_profiles set enabled=false where id=$1',[cashier.id]);expect((await app.inject({url:'/api/v1/me',headers:{authorization:'Bearer cashier'}})).statusCode).toBe(403);await pool.query('update wifi.staff_profiles set enabled=true where id=$1',[cashier.id]);});
it('inventory responses contain no encrypted/digest/raw codes',async()=>{const r=await app.inject({url:'/api/v1/vouchers',headers:{authorization:'Bearer admin'}});expect(r.statusCode).toBe(200);expect(r.body).not.toMatch(/code_encrypted|code_digest/);expect(r.json().items[0]).not.toHaveProperty('code');expect(r.headers['cache-control']).toBe('no-store');});
it('generated stock is excluded from revenue and Tanzania boundaries work',async()=>{const headers={authorization:'Bearer admin'};const before=(await app.inject({url:'/api/v1/reports/sales',headers})).json();await stock(10);const after=(await app.inject({url:'/api/v1/reports/sales',headers})).json();expect(after.gross_tzs).toBe(before.gross_tzs);const b=(await pool.query("select '2026-09-19'::timestamp at time zone 'Africa/Dar_es_Salaam' boundary")).rows[0];expect(b.boundary.toISOString()).toBe('2026-09-18T21:00:00.000Z');});
it('anonymous Supabase roles cannot access business tables',async()=>{const c=await pool.connect();try{await c.query('begin');await c.query('set local role anon');await expect(c.query('select * from wifi.vouchers')).rejects.toThrow('permission denied');await c.query('rollback');}finally{c.release();}});

it('snapshots package speeds into vouchers and sale items without changing old terms',async()=>{
 const s=await stock();await pool.query('update wifi.packages set download_mbps=10,upload_mbps=5 where id=$1',[s.p.id]);
 const b=await generateBatch(admin,{package_id:s.p.id,quantity:1});const codes=await reveal(admin,{batch_id:b.id});expect(codes[0]).toMatchObject({download_mbps:10,upload_mbps:5});
 expect((await reveal(admin,{batch_id:s.b.id}))[0].download_mbps).toBeNull();
 await pool.query('update wifi.packages set download_mbps=20 where id=$1',[s.p.id]);
 await expect(pool.query('update wifi.vouchers set download_mbps=20 where batch_id=$1',[b.id])).rejects.toThrow('immutable');
 const reservation=await reserve(admin,{package_id:s.p.id,quantity:2});const sale=await sell(admin,{reservation_id:reservation.id,cash_received:true},randomUUID());
 expect((await pool.query('select download_mbps,upload_mbps from wifi.manual_sale_items where sale_id=$1 and voucher_id=$2',[sale.id,codes[0].id])).rows[0]).toEqual({download_mbps:10,upload_mbps:5});
});
it('denies cashiers access to router diagnostics',async()=>{expect((await app.inject({method:'POST',url:'/api/v1/integrations/mikrotik/test',headers:{authorization:'Bearer cashier'},payload:{}})).statusCode).toBe(403);});

// Real database tests for live MikroTik authentication; never touch the hosted DB.
const radiusConfigForTests={secret:'c'.repeat(64),clientIp:'10.77.0.2',hotspot:'babu-hotspot',group:'babu-vouchers',defaultDownload:5,defaultUpload:2};
function proof(code:string,clientMac='AA:00:00:00:00:11',password=normalize(code)) {const challenge=Buffer.alloc(16,7),id=Buffer.from([19]);return {username:normalize(code),clientMac,challenge,chapPassword:Buffer.concat([id,createHash('md5').update(id).update(password).update(challenge).digest()])};}
async function live<T>(fn:()=>Promise<T>){const old={provider:process.env.NETWORK_PROVIDER,mode:process.env.OMADA_MODE,enabled:process.env.MIKROTIK_RADIUS_ENABLED};process.env.NETWORK_PROVIDER='mikrotik';process.env.OMADA_MODE='live';process.env.MIKROTIK_RADIUS_ENABLED='true';try{return await fn();}finally{for(const [k,v] of Object.entries({NETWORK_PROVIDER:old.provider,OMADA_MODE:old.mode,MIKROTIK_RADIUS_ENABLED:old.enabled}))if(v===undefined)delete process.env[k];else process.env[k]=v;}}
it('RADIUS rejects unsold codes and wrong CHAP proof without starting validity',async()=>live(async()=>{const s=await stock();expect(await authorizeRadius(proof(s.codes[0].code),radiusConfigForTests)).toBeNull();const v=await sold();expect(await authorizeRadius(proof(v.codes[0].code,undefined,'wrong'),radiusConfigForTests)).toBeNull();expect((await pool.query('select * from wifi.access_grants where voucher_id=$1',[v.codes[0].id])).rowCount).toBe(0);}));
it('RADIUS binds one device under races and keeps the exact deadline on retransmission',async()=>live(async()=>{const s=await sold();const results=await Promise.all([authorizeRadius(proof(s.codes[0].code),radiusConfigForTests),authorizeRadius(proof(s.codes[0].code,'AA:00:00:00:00:12'),radiusConfigForTests)]);expect(results.filter(Boolean)).toHaveLength(1);const g=(await pool.query('select * from wifi.access_grants where voucher_id=$1',[s.codes[0].id])).rows[0];expect(g).toMatchObject({provider:'mikrotik-radius',state:'ACTIVE'});const again=await authorizeRadius(proof(s.codes[0].code,g.client_mac),radiusConfigForTests);expect(again?.expiresAt).toEqual(g.proposed_expires_at);expect(g.expires_at).toEqual(g.proposed_expires_at);expect((await pool.query("select * from wifi.audit_logs where entity_id=$1 and action='MIKROTIK_VOUCHER_ACTIVATED'",[g.id])).rowCount).toBe(1);await expect(pool.query("update wifi.access_grants set proposed_expires_at=proposed_expires_at+interval '1 day' where id=$1",[g.id])).rejects.toThrow('immutable');await expect(reverse(admin,s.sale.id,'Cannot reverse activated voucher')).rejects.toThrow('unused');}));
it('RADIUS rejects expired and revoked grants permanently, regardless of worker housekeeping',async()=>live(async()=>{const s=await sold();await pool.query("insert into wifi.access_grants(voucher_id,client_mac,state,provider,proposed_expires_at,expires_at,activated_at) values($1,$2,'ACTIVE','mikrotik-radius',now()-interval '1 second',now()-interval '1 second',now()-interval '1 hour')",[s.codes[0].id,'AA:00:00:00:00:11']);expect(await authorizeRadius(proof(s.codes[0].code),radiusConfigForTests)).toBeNull();const g=(await pool.query('select * from wifi.access_grants where voucher_id=$1',[s.codes[0].id])).rows[0];expect(g.state).toBe('EXPIRED');await expect(pool.query("update wifi.access_grants set state='ACTIVE' where id=$1",[g.id])).rejects.toThrow('cannot be restored');const r=await sold();await authorizeRadius(proof(r.codes[0].code),radiusConfigForTests);const id=(await pool.query('select id from wifi.access_grants where voucher_id=$1',[r.codes[0].id])).rows[0].id;await revoke(admin,id,'Test revocation');expect(await authorizeRadius(proof(r.codes[0].code),radiusConfigForTests)).toBeNull();}));
it('RADIUS does not convert old simulated activations into real entitlements',async()=>{const s=await sold();await activate(s.codes[0].code);await live(async()=>{expect(await authorizeRadius(proof(s.codes[0].code,ctx.clientMac),radiusConfigForTests)).toBeNull();await expect(redeem(s.codes[0].code,'anything')).rejects.toThrow('sign-in page');});});
it('RADIUS uses voucher speed snapshots and never activates while in mock mode',async()=>{const s=await stock();await pool.query('update wifi.packages set download_mbps=12,upload_mbps=3 where id=$1',[s.p.id]);const b=await generateBatch(admin,{package_id:s.p.id,quantity:1}),codes=await reveal(admin,{batch_id:b.id});const reservation=await reserve(admin,{package_id:s.p.id,quantity:2});await sell(admin,{reservation_id:reservation.id,cash_received:true},randomUUID());expect(await authorizeRadius(proof(codes[0].code),radiusConfigForTests)).toBeNull();await pool.query('update wifi.packages set download_mbps=20 where id=$1',[s.p.id]);await live(async()=>expect(await authorizeRadius(proof(codes[0].code),radiusConfigForTests)).toMatchObject({download:12,upload:3}));});
it('accounting duplicates and out-of-order packets neither inflate totals nor reopen sessions',async()=>live(async()=>{const s=await sold();await authorizeRadius(proof(s.codes[0].code),radiusConfigForTests);const event={username:s.codes[0].code,clientMac:'AA:00:00:00:00:11',sessionId:randomUUID(),status:'Interim-Update' as const,seconds:60,upload:'4000000000',download:'9000000000',terminateCause:null};await recordAccounting(event,'10.77.0.2');await recordAccounting(event,'10.77.0.2');await recordAccounting({...event,status:'Stop',seconds:120,upload:'4500000000',terminateCause:'Session-Timeout'},'10.77.0.2');await recordAccounting({...event,status:'Start',seconds:0,upload:'0',download:'0'},'10.77.0.2');const row=(await pool.query('select * from wifi.network_sessions where session_id=$1',[event.sessionId])).rows[0];expect(row.upload_bytes).toBe('4500000000');expect(row.download_bytes).toBe('9000000000');expect(row.stopped_at).toBeTruthy();const response=await app.inject({url:'/api/v1/sessions',headers:{authorization:'Bearer admin'}});expect(response.statusCode).toBe(200);expect(response.json().items[0].upload_bytes).toBe('4500000000');expect(response.body).not.toContain(normalize(s.codes[0].code));expect((await app.inject({url:'/api/v1/sessions',headers:{authorization:'Bearer cashier'}})).statusCode).toBe(403);}));

it('runtime mode follows the API adapter for both staff roles and stays private',async()=>live(async()=>{
 for(const role of ['admin','cashier']){
  const r=await app.inject({url:'/api/v1/runtime',headers:{authorization:'Bearer '+role}});
  expect(r.statusCode).toBe(200);expect(r.json()).toEqual({mode:'mock',provider:'mikrotik',radius_enabled:false});
 }
 expect((await app.inject('/api/v1/runtime')).statusCode).toBe(401);
 const liveApp=await buildApp({adapter:new MikroTikRadiusAdapter(),verifyToken:async()=>cashier.id});
 try{const r=await liveApp.inject({url:'/api/v1/runtime',headers:{authorization:'Bearer cashier'}});expect(r.json()).toEqual({mode:'live',provider:'mikrotik',radius_enabled:true});}finally{await liveApp.close();}
}));
