import {createHash,createHmac,randomBytes} from 'node:crypto';
import {it,expect,vi} from 'vitest';
import {radius,decodeVoucherRequest,voucherReply,makeRadiusHandler,radiusConfig,type RadiusConfig} from '../packages/network/src/radius.ts';
import {decodeAccounting,makeAccountingHandler} from '../packages/network/src/accounting.ts';
const config:RadiusConfig={secret:'c'.repeat(64),clientIp:'10.77.0.2',hotspot:'babu-hotspot',group:'babu-vouchers',defaultDownload:5,defaultUpload:2};
function request(extra:any[]=[],ma=true){return radius.encode({code:'Access-Request',secret:config.secret,identifier:17,add_message_authenticator:ma,attributes:[['NAS-IP-Address',config.clientIp],['Called-Station-Id',config.hotspot],['Calling-Station-Id','AA:BB:CC:DD:EE:01'],['User-Name','ABCDEFGHJKLMNPQR'],['CHAP-Password',Buffer.alloc(17,1)],['CHAP-Challenge',Buffer.alloc(16,2)],...extra]});}
it('requires an authenticated request from the specific router and HotSpot',()=>{const raw=request();expect(decodeVoucherRequest(raw,config.clientIp,config)?.request.username).toBe('ABCDEFGHJKLMNPQR');expect(decodeVoucherRequest(raw,'10.77.0.3',config)).toBeNull();expect(decodeVoucherRequest(raw,config.clientIp,{...config,hotspot:'other'})).toBeNull();expect(decodeVoucherRequest(request([],false),config.clientIp,config)).toBeNull();const tampered=Buffer.from(raw);tampered[4]^=1;expect(decodeVoucherRequest(tampered,config.clientIp,config)).toBeNull();});
it('rejects duplicate security attributes, malformed TLVs, PAP and proxy-state',()=>{for(const extra of [[['User-Name','different']],[['Message-Authenticator',Buffer.alloc(16)]],[['User-Password','code']],[['Proxy-State',Buffer.from('proxy')]]])expect(decodeVoucherRequest(request(extra),config.clientIp,config)).toBeNull();for(const raw of [Buffer.alloc(10),Buffer.alloc(5000),request().subarray(0,25)])expect(decodeVoucherRequest(raw,config.clientIp,config)).toBeNull();});
it('signs replies independently verifiable from RFC response and HMAC calculations',()=>{const raw=request(),packet=decodeVoucherRequest(raw,config.clientIp,config)!.packet,reply=voucherReply(packet,{expiresAt:new Date(100000),download:5,upload:2},config,10000);expect(radius.verify_response({request:raw,response:reply,secret:config.secret})).toBe(true);const expected=createHash('md5').update(reply.subarray(0,4)).update(raw.subarray(4,20)).update(reply.subarray(20)).update(config.secret).digest();expect(reply.subarray(4,20)).toEqual(expected);let offset=20;while(reply[offset]!==80)offset+=reply[offset+1];const copy=Buffer.from(reply);raw.copy(copy,4,4,20);copy.fill(0,offset+2,offset+18);expect(reply.subarray(offset+2,offset+18)).toEqual(createHmac('md5',config.secret).update(copy).digest());const parsed=radius.decode({packet:reply,secret:config.secret});expect(parsed.attributes['Session-Timeout']).toBe(85);expect(parsed.attributes['Port-Limit']).toBe(1);const vendor=parsed.raw_attributes.find((a:any)=>a[0]===26)[1];expect(vendor.readUInt32BE()).toBe(14988);expect(vendor.toString()).toContain('2M/5M');});
it('never issues a zero/negative allowance and recalculates remaining time on retry',()=>{const p=decodeVoucherRequest(request(),config.clientIp,config)!.packet;const d={expiresAt:new Date(100000),download:5,upload:2};const decode=(now:number)=>radius.decode({packet:voucherReply(p,d,config,now),secret:config.secret});expect(decode(10000).attributes['Session-Timeout']).toBe(85);expect(decode(60000).attributes['Session-Timeout']).toBe(35);expect(decode(96000).code).toBe('Access-Reject');});
it('fails closed when database authorization fails and rejects malformed packets before database work',async()=>{const auth=vi.fn().mockRejectedValue(new Error('secret database URL'));const handle=makeRadiusHandler(config,auth);expect(await handle(Buffer.alloc(5),config.clientIp)).toBeNull();expect(auth).not.toHaveBeenCalled();const reply=await handle(request(),config.clientIp);expect(radius.decode({packet:reply!,secret:config.secret}).code).toBe('Access-Reject');expect(reply!.toString()).not.toContain('database');});
it('drops late accepts instead of extending a session after the NAS timeout',async()=>{vi.useFakeTimers();try{const handle=makeRadiusHandler(config,async()=>{vi.advanceTimersByTime(2600);return {expiresAt:new Date(Date.now()+60000),download:5,upload:2};});expect(await handle(request(),config.clientIp)).toBeNull();}finally{vi.useRealTimers();}});
it('bounds requests per device before database authorization',async()=>{const auth=vi.fn().mockResolvedValue(null),handle=makeRadiusHandler(config,auth);for(let i=0;i<40;i++)await handle(request(),config.clientIp);expect(auth).toHaveBeenCalledTimes(30);});
it('requires explicit live-mode configuration and a strong new shared secret',()=>{const env={NETWORK_PROVIDER:'mikrotik',OMADA_MODE:'live',MIKROTIK_RADIUS_ENABLED:'true',MIKROTIK_RADIUS_SECRET:config.secret,MIKROTIK_RADIUS_CLIENT_IP:config.clientIp,MIKROTIK_HOTSPOT_SERVER:config.hotspot,MIKROTIK_RADIUS_GROUP:config.group,MIKROTIK_DEFAULT_DOWNLOAD_MBPS:'5',MIKROTIK_DEFAULT_UPLOAD_MBPS:'2'};expect(radiusConfig(env)).toEqual(config);for(const change of [{OMADA_MODE:'mock'},{MIKROTIK_RADIUS_SECRET:'short'},{MIKROTIK_DEFAULT_UPLOAD_MBPS:'NaN'}])expect(()=>radiusConfig({...env,...change})).toThrow();});
function accounting(extra:any[]=[]){return radius.encode({code:'Accounting-Request',secret:config.secret,attributes:[['NAS-IP-Address',config.clientIp],['Called-Station-Id',config.hotspot],['Calling-Station-Id','AA:BB:CC:DD:EE:01'],['User-Name','ABCDEFGHJKLMNPQR'],['Acct-Session-Id','session-1'],['Acct-Status-Type','Interim-Update'],['Acct-Session-Time',60],['Acct-Input-Octets',12],['Acct-Input-Gigawords',1],['Acct-Output-Octets',45],...extra]});}
it('validates accounting authenticator and preserves 64-bit byte counters',()=>{const raw=accounting(),decoded=decodeAccounting(raw,config.clientIp,config);expect(decoded?.event).toMatchObject({upload:'4294967308',download:'45',seconds:60});const bad=Buffer.from(raw);bad[8]^=1;expect(decodeAccounting(bad,config.clientIp,config)).toBeNull();expect(decodeAccounting(raw,'1.2.3.4',config)).toBeNull();});
it('acknowledges accounting only after durable storage',async()=>{const raw=accounting();const good=await makeAccountingHandler(config,async()=>{})(raw,config.clientIp);expect(radius.verify_response({request:raw,response:good!,secret:config.secret})).toBe(true);expect(await makeAccountingHandler(config,async()=>{throw new Error('db down');})(raw,config.clientIp)).toBeNull();});
it('rejects random signed-shape packets without crashing',()=>{for(let i=0;i<100;i++){const raw=randomBytes(20+i);raw[0]=1;raw.writeUInt16BE(raw.length,2);expect(decodeVoucherRequest(raw,config.clientIp,config)).toBeNull();}});
