import 'dotenv/config';
import {mkdir, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)).replaceAll('$', '&#36;');
const brand = escape(process.env.WIFI_BRAND || 'JIACHIE WIFI');
const support = escape(process.env.WIFI_SUPPORT_CONTACT || 'Ask the shop attendant for help.');
const style = `*{box-sizing:border-box}body{margin:0;background:#f2f5f1;color:#153f37;font:16px/1.6 system-ui,sans-serif;min-height:100vh;display:grid;place-items:center;padding:24px}main{width:100%;max-width:440px}header{font-weight:800;letter-spacing:.12em;text-align:center;margin:0 0 26px}section{background:white;border:1px solid #dce5df;border-radius:24px;padding:32px;box-shadow:0 16px 48px #163e3710}h1{font-size:34px;line-height:1.15;letter-spacing:-.04em;margin:12px 0 16px}h2{font-size:20px}p{color:#60756d}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:#507568}label{display:block;font-weight:650;margin:24px 0 8px}input{width:100%;border:1px solid #a9c0b4;border-radius:12px;padding:16px;font-size:19px;text-transform:uppercase;font-family:monospace;letter-spacing:.06em}input:focus{outline:3px solid #d8edb0;border-color:#205c49}button,.button{display:block;text-align:center;width:100%;padding:15px;margin-top:16px;background:#195648;border:0;border-radius:12px;color:white;font:700 16px system-ui;cursor:pointer;text-decoration:none}button:disabled{opacity:.65}.note{font-size:13px;padding-top:16px;border-top:1px solid #e3eae5;margin-top:28px}.error{padding:12px;background:#fff1e9;color:#8d351b;border-radius:10px}.detail{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #e3eae5;padding:12px 0}.small,footer{font-size:12px}footer{text-align:center;color:#657970;margin-top:20px}@media(max-width:380px){section{padding:24px}h1{font-size:30px}}`;
function page(title: string, content: string, scripts = '') { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${title} · ${brand}</title><style>${style}</style></head><body><main><header>◉ ${brand}</header><section>${content}</section><footer>${brand} · Prepaid internet, made simple.</footer></main>${scripts}</body></html>`; }
const login = page('Connect', `<p class="eyebrow">Welcome to your connection</p><h1>A little code.<br>A world online.</h1><p>Enter your voucher and enjoy the shop Wi-Fi.</p>$(if error)<p class="error" role="alert">We couldn’t connect you. Check your voucher, or ask the attendant if it has expired or was already used on another device.</p>$(endif)<p id="problem" class="error" role="alert" hidden></p><form id="voucher-form"><label for="code">Your voucher code</label><input id="code" name="voucher" placeholder="XXXX-XXXX-XXXX-XXXX" autocomplete="off" autocapitalize="characters" spellcheck="false" maxlength="40" required><button id="connect" type="submit">Connect to Wi-Fi →</button></form><form id="router-login" action="$(link-login-only)" method="post"><input type="hidden" name="username"><input type="hidden" name="password"><input type="hidden" name="dst" value="http://10.78.0.1/status"><input type="hidden" name="popup" value="false"></form><noscript><p class="error">Enable JavaScript to securely submit your voucher.</p></noscript><div class="note"><strong>No voucher yet?</strong><p>Buy one from the attendant. One voucher works on one device; time continues while disconnected.</p><p>${support}</p></div>`, `<script src="/md5.js"></script><script>document.getElementById('voucher-form').addEventListener('submit',function(e){e.preventDefault();var code=document.getElementById('code').value.toUpperCase().replace(/[\\s-]/g,'');var error=document.getElementById('problem');if(!/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{16}$/.test(code)){error.textContent='Enter all 16 characters from your voucher.';error.hidden=false;return;}$(if chap-id)var form=document.getElementById('router-login');if(typeof hexMD5!=='function'){error.textContent='Sign-in is unavailable. Please ask the attendant.';error.hidden=false;return;}form.elements.username.value=code;form.elements.password.value=hexMD5('$(chap-id)'+code+'$(chap-challenge)');document.getElementById('connect').disabled=true;document.getElementById('connect').textContent='Connecting…';form.submit();$(else)error.textContent='Secure voucher sign-in is not configured. Please ask the attendant.';error.hidden=false;$(endif)});</script>`);
const status = page('Connected', `<p class="eyebrow">You’re connected</p><h1>Your time.<br>Your connection.</h1><p>You can now browse the internet.</p><div class="detail"><span>Session time remaining</span><strong>$(session-time-left)</strong></div><div class="detail"><span>Connected for</span><strong>$(uptime)</strong></div><div class="detail"><span>Downloaded</span><strong>$(bytes-out-nice)</strong></div><div class="detail"><span>Uploaded</span><strong>$(bytes-in-nice)</strong></div><a class="button" href="$(link-logout)">Disconnect</a><p class="note">Disconnecting does not pause your voucher. Reconnect with the same code and device before its expiry.</p><p class="small">${support}</p>`);
const logout = page('Disconnected', `<p class="eyebrow">Connection ended</p><h1>You’re offline.</h1><p>If your voucher still has time remaining, sign in again on this device. Expired vouchers cannot restart.</p><a class="button" href="$(link-login)">Return to sign-in →</a><p class="note">${support}</p>`);
const alogin = page('Connected', `<p class="eyebrow">You’re connected</p><h1>Welcome online.</h1><a class="button" href="$(link-status)">View connection →</a>`);
const dir = resolve('dist/hotspot'); await mkdir(dir, {recursive: true});
for (const [name, content] of Object.entries({'login.html':login,'status.html':status,'logout.html':logout,'alogin.html':alogin,'flogin.html':login})) await writeFile(resolve(dir,name),content);
console.info('Branded pages written to dist/hotspot. Preserve the router’s existing md5.js when uploading.');
