import {isIP} from 'node:net';
import {pool,tx,audit,requireValue,type Staff} from './index.ts';
import {digest,normalize,token} from './crypto.ts';
import type {Adapter,Context} from '../../omada/src/index.ts';
const generic='Voucher cannot be used. Check the code or contact the attendant.';
export function mac(value:string){const s=value.toUpperCase().replaceAll('-',':');requireValue(/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/.test(s)&&!['00:00:00:00:00:00','FF:FF:FF:FF:FF:FF'].includes(s),400,'Invalid network context. Rejoin the Wi-Fi.');return s;}
export function validateContext(input:Context):Context{
 const c={clientMac:mac(input.clientMac),apMac:mac(input.apMac),ssidName:input.ssidName,radioId:input.radioId,site:input.site,...(input.clientIp?{clientIp:input.clientIp}:{})};
 requireValue(c.site===process.env.PORTAL_SITE&&c.ssidName===process.env.PORTAL_SSID&&(process.env.PORTAL_AP_MACS||'').split(',').map(mac).includes(c.apMac)&&/^[0-2]$/.test(c.radioId),400,'This Wi-Fi network is not configured. Contact the attendant.');
 requireValue(!c.clientIp||isIP(c.clientIp)>0,400,'Invalid network address');if(process.env.OMADA_MODE==='live'&&process.env.OMADA_PROFILE==='modern')requireValue(c.clientIp,400,'Missing network address');return c;
}
export async function createContext(input:Context){const context=validateContext(input),value=token();await pool.query("insert into wifi.portal_contexts(token_digest,context,expires_at) values($1,$2,now()+interval '10 minutes')",[digest(value,'PORTAL_CONTEXT_SECRET'),context]);return {context_token:value,expires_in:600};}
export async function redeem(code:string,contextToken:string){const lookup=digest(normalize(code));return tx(async db=>{
 const c=(await db.query('select * from wifi.portal_contexts where token_digest=$1 and expires_at>now()',[digest(contextToken,'PORTAL_CONTEXT_SECRET')])).rows[0];requireValue(c,400,'Network session expired. Rejoin the Wi-Fi.');
 const v=(await db.query('select * from wifi.vouchers where code_digest=$1 for update',[lookup])).rows[0];requireValue(v&&v.inventory_state==='SOLD',400,generic);
 let grant=(await db.query('select * from wifi.access_grants where voucher_id=$1 for update',[v.id])).rows[0];
 if(grant){requireValue(grant.client_mac===c.context.clientMac&&!['EXPIRED','REVOKED'].includes(grant.state)&&new Date(grant.proposed_expires_at).getTime()>Date.now(),400,generic);}
 else{grant=(await db.query("insert into wifi.access_grants(voucher_id,client_mac,state,proposed_expires_at) values($1,$2,'PENDING',now()+make_interval(mins=>$3)) returning *",[v.id,c.context.clientMac,v.duration_minutes])).rows[0];}
 const open=(await db.query("select 1 from wifi.authorization_attempts where grant_id=$1 and state in ('QUEUED','SENDING','NEEDS_REVIEW')",[grant.id])).rowCount;
 if(!open){const attempt=(await db.query("insert into wifi.authorization_attempts(grant_id,context,deadline,state) values($1,$2,$3,'QUEUED') returning id",[grant.id,c.context,grant.proposed_expires_at])).rows[0];await db.query("update wifi.access_grants set state='PENDING',updated_at=now() where id=$1",[grant.id]);await db.query('insert into wifi.jobs(attempt_id) values($1)',[attempt.id]);}
 const value=token();await db.query("insert into wifi.portal_status_tokens(token_digest,grant_id,expires_at) values($1,$2,now()+interval '20 minutes')",[digest(value,'PORTAL_CONTEXT_SECRET'),grant.id]);return {status_token:value,state:open&&grant.state==='NEEDS_REVIEW'?'NEEDS_REVIEW':'PENDING'};
});}
export async function status(value:string){const g=(await pool.query('select g.state,g.expires_at,g.proposed_expires_at,a.state attempt_state from wifi.portal_status_tokens t join wifi.access_grants g on g.id=t.grant_id left join lateral(select state from wifi.authorization_attempts where grant_id=g.id order by created_at desc limit 1)a on true where t.token_digest=$1 and t.expires_at>now()',[digest(value,'PORTAL_CONTEXT_SECRET')])).rows[0];requireValue(g,404,'Status link expired. Re-enter the voucher on your Wi-Fi device.');return {state:new Date(g.proposed_expires_at).getTime()<=Date.now()&&g.state!=='REVOKED'?'EXPIRED':g.state,expires_at:g.expires_at,attempt_state:g.attempt_state};}
export async function processOne(adapter:Adapter){
 // A recovered SENDING job is ambiguous: the controller may already have accepted it.
 const work=await tx(async db=>{const j=(await db.query("select * from wifi.jobs where (state='READY' and due_at<=now()) or (state='LEASED' and lease_until<now()) order by due_at for update skip locked limit 1")).rows[0];if(!j)return null;
 const a=(await db.query('select * from wifi.authorization_attempts where id=$1 for update',[j.attempt_id])).rows[0];
 if(j.state==='LEASED'||a.state==='SENDING'){await db.query("update wifi.authorization_attempts set state='NEEDS_REVIEW',evidence=$2,updated_at=now() where id=$1",[a.id,{code:'WORKER_INTERRUPTED_AFTER_CLAIM'}]);await db.query("update wifi.access_grants set state=case when state='REVOKED' then state else 'NEEDS_REVIEW' end,updated_at=now() where id=$1",[a.grant_id]);await db.query("update wifi.jobs set state='DONE' where id=$1",[j.id]);return null;}
 const g=(await db.query('select * from wifi.access_grants where id=$1 for update',[a.grant_id])).rows[0];
 if(g.state==='REVOKED'||new Date(a.deadline).getTime()<=Date.now()){await db.query("update wifi.authorization_attempts set state='CANCELLED',updated_at=now() where id=$1",[a.id]);await db.query("update wifi.jobs set state='DONE' where id=$1",[j.id]);return null;}
 await db.query("update wifi.jobs set state='LEASED',lease_until=now()+interval '45 seconds' where id=$1",[j.id]);await db.query("update wifi.authorization_attempts set state='SENDING',updated_at=now() where id=$1",[a.id]);return {job:j,attempt:a};});
 if(!work)return false;let outcome;try{outcome=await adapter.authorize(work.attempt.context,new Date(work.attempt.deadline));}catch{outcome={status:'unknown',evidence:{code:'ADAPTER_FAILURE'}};}
 await tx(async db=>{const a=(await db.query('select * from wifi.authorization_attempts where id=$1 for update',[work.attempt.id])).rows[0];if(a.state!=='SENDING')return;
 const state=outcome.status==='accepted'?'ACCEPTED':outcome.status==='rejected'?'REJECTED':'NEEDS_REVIEW';await db.query('update wifi.authorization_attempts set state=$2,evidence=$3,updated_at=now() where id=$1',[a.id,state,outcome.evidence]);
 await db.query("update wifi.access_grants set state=case when state='REVOKED' then state when proposed_expires_at<=now() then 'EXPIRED' when $2='ACCEPTED' then 'ACTIVE' else 'NEEDS_REVIEW' end,expires_at=case when $2='ACCEPTED' then proposed_expires_at else expires_at end,activated_at=case when $2='ACCEPTED' then coalesce(activated_at,created_at) else activated_at end,updated_at=now() where id=$1",[a.grant_id,state]);await db.query("update wifi.jobs set state='DONE' where id=$1",[work.job.id]);await audit(db,null,'AUTHORIZATION_'+state,a.grant_id,outcome.evidence);
 });return true;
}
export async function housekeeping(){await pool.query("update wifi.access_grants set state='EXPIRED',updated_at=now() where proposed_expires_at<=now() and state in ('PENDING','ACTIVE','NEEDS_REVIEW')");await pool.query('delete from wifi.portal_contexts where expires_at<now()');await pool.query('delete from wifi.portal_status_tokens where expires_at<now()');/* Financial idempotency records retained with sales: no late duplicate receipts. */}
export async function revoke(staff:Staff,id:string,reason:string){return tx(async db=>{const r=await db.query("update wifi.access_grants set state='REVOKED',updated_at=now() where id=$1 returning id",[id]);requireValue(r.rowCount,404,'Grant not found');await audit(db,staff.id,'ACCESS_REVOKED',id,{reason});return {ok:true,message:'Future authorization blocked. Network access may continue until controller expiry; disconnect is unsupported.'};});}
export async function review(staff:Staff,id:string,input:{decision:'ACCEPTED'|'REJECTED';reason:string}){return tx(async db=>{const a=(await db.query('select * from wifi.authorization_attempts where id=$1 for update',[id])).rows[0];requireValue(a&&a.state==='NEEDS_REVIEW',409,'Only ambiguous attempts need this review');await db.query('update wifi.authorization_attempts set state=$2,review_note=$3,reviewed_by=$4,updated_at=now() where id=$1',[id,input.decision,input.reason,staff.id]);await db.query("update wifi.access_grants set state=case when state='REVOKED' then state when proposed_expires_at<=now() then 'EXPIRED' when $2='ACCEPTED' then 'ACTIVE' else 'NEEDS_REVIEW' end,expires_at=case when $2='ACCEPTED' then proposed_expires_at else expires_at end,activated_at=case when $2='ACCEPTED' then coalesce(activated_at,created_at) else activated_at end,updated_at=now() where id=$1",[a.grant_id,input.decision]);await audit(db,staff.id,'ATTEMPT_REVIEWED',id,input);return {ok:true};});}
