<script lang="ts">
import Icon from '$lib/components/Icon.svelte';
import SellerContact from '$lib/components/SellerContact.svelte';
import {onMount} from 'svelte';import {enhance} from '$app/forms';
let {data,form}=$props();let busy=$state(false);let status=$state<any>(null);let timer:ReturnType<typeof setTimeout>;let refreshError=$state('');
async function refresh(){if(!form?.status_token)return;try{const response=await fetch('/portal/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status_token:form.status_token})});const result=await response.json();if(!response.ok)throw new Error(result.error);status=result;refreshError='';if(result.state==='PENDING')timer=setTimeout(refresh,2000);}catch{refreshError='Connection interrupted. Tap refresh to check your access.';}}
$effect(()=>{if(form?.status_token){status=null;refresh();}return()=>clearTimeout(timer);});onMount(()=>()=>clearTimeout(timer));
const expiry=(d:string)=>new Intl.DateTimeFormat('en-TZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Dar_es_Salaam'}).format(new Date(d));
</script>
<svelte:head><title>Connect · {data.brand}</title><meta name="robots" content="noindex"></svelte:head>
<main class="portal-wrap"><div class="portal-brand brand"><span class="brand-mark"><img src="/logo.webp" alt="" width="38" height="38"></span>{data.brand}</div><section class="portal-card">{#if data.mock}<div class="simulation">SIMULATION · No real internet is authorized</div>{/if}<div class="portal-body"><div class="wifi-symbol" aria-hidden="true"><Icon size={26}/></div><p class="eyebrow">WELCOME TO YOUR CONNECTION</p><h1>Let’s get you online.</h1><p>Enter your voucher to connect to the shop Wi-Fi.</p>
{#if data.mikrotik}<div class="notice"><p>Join the shop Wi-Fi, then open its sign-in page to enter your voucher.</p><a class="button full" href="http://10.78.0.1/login">Open Wi-Fi sign-in →</a><p class="small">This address works while connected to the shop Wi-Fi.</p></div>{:else if form?.status_token}<div aria-live="polite" class="connection-state"><h2>{status?.state==='ACTIVE'?'You’re authorized':status?.state==='NEEDS_REVIEW'?'We’re checking your access':status?.state==='EXPIRED'?'Your time has ended':status?.state==='REVOKED'?'Access is unavailable':'Connecting…'}</h2>{#if status?.state==='ACTIVE'}<p>Your entitlement ends <strong>{expiry(status.expires_at)}</strong>.</p><p class="small">You can now try opening your browser. Authorization is not a live connection test.</p>{:else if status?.state==='NEEDS_REVIEW'}<p>Please speak to the attendant. Your original time limit is protected; another device cannot use this code.</p>{:else if status?.state==='EXPIRED'}<p>Purchase another voucher from the attendant to continue.</p>{:else}<p>Keep this page open while we confirm your authorization.</p>{/if}{#if refreshError}<p role="alert">{refreshError}</p>{/if}<button class="button secondary" onclick={refresh}>Refresh status</button></div>
{:else}{#if data.context_error}<p class="notice" role="alert">{data.context_error}</p>{/if}{#if form?.error}<p class="notice error" role="alert">{form.error}</p>{/if}<form method="POST" use:enhance={()=>{busy=true;return async({update})=>{await update();busy=false;};}}><input type="hidden" name="context_token" value={data.context_token}><label for="voucher">Your voucher code</label><input id="voucher" class="code-input" name="code" placeholder="XXXX-XXXX-XXXX-XXXX" autocomplete="off" autocapitalize="characters" spellcheck="false" minlength="16" maxlength="40" required disabled={!data.context_token||busy}><button class="button full" disabled={!data.context_token||busy}>{busy?'Connecting…':'Connect to Wi-Fi →'}</button></form>{/if}
<a class="button secondary full" href="/buy">Buy a voucher with mobile money →</a><SellerContact/><p class="small muted">Hyphens in your code are optional.</p><p class="small muted">One voucher. One device. Time continues while disconnected.</p>{#if data.support}<p class="small">Need help? {data.support}</p>{/if}</div></section><p class="portal-footer">Simple access. Your time, your connection.</p></main>
